services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: hhansegrill
    volumes:
      - payload_postgres_data:/var/lib/postgresql/data

volumes:
  payload_postgres_data:
